#!/usr/bin/env bash

export BASH_SILENCE_DEPRECATION_WARNING=1

PATH="/opt/homebrew/bin":$PATH                    # homebrew
PATH="${HOME}/.cargo/bin":$PATH                   # rust
PATH="${GOPATH}/bin:$PATH"                        # golang
PATH="${GOROOT}/bin:$PATH"                        # golang
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH" # krew
PATH=${HOME}/.local/bin:$PATH                     # local scripts
PATH="/opt/local/bin:/opt/local/sbin:$PATH"       # macports

export GOPATH="${HOME}/.go"
GOROOT="$("$(brew --prefix)/bin/brew" --prefix golang)/libexec"
export GOROOT

export HOMEBREW_PREFIX="/opt/homebrew"
export BASH_COMPLETION_DIR="${HOME}/.bash_completion.d" # read by bash-completion to load custom completion files

eval "$("$(brew --prefix)/bin/brew" shellenv bash)"

if [[ -s "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]]; then
  source "$(brew --prefix)/etc/profile.d/bash_completion.sh"
fi

if [[ -d "$(brew --prefix)/opt/ruby/bin" ]]; then
  PATH=/"$(brew --prefix)/opt/ruby/bin:$PATH"
  PATH="$(gem environment gemdir)/bin:$PATH"
fi

if [[ -d "${HOME}/.cargo" ]]; then
  source "${HOME}/.cargo/env"
fi

eval "$(mise activate bash)"
export PATH

source "${HOME}/.bashrc"
