# improve colors
set -g default-terminal 'xterm-256color'
set-option -g default-shell /usr/bin/fish

# act like vim
set -g focus-events on
set -g mode-keys vi
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+
bind-key v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"

# alt shortcuts
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind-key a last-window
bind-key q display-panes

unbind C-b
set -g prefix C-a
bind C-a send-prefix

# turn off mouse support
set -g mouse off

# Start numbering at 1
set -g base-index 1
set-window-option -g pane-base-index 1

# renumber windows sequentially after closing any of them
set-option -g renumber-windows on

# Allow for faster key repitition
set -s escape-time 0

# Activity Monitoring
setw -g monitor-activity on
set -g visual-activity on

# clock
#set-window-option -g clock-mode-colour colour64 #green

# status bar
#set -g status-left '#[fg=green]%H:%M | '
#set -g status-right '%a %h-%d %H:%M '
set -g status-position top

# increase scrollback lines
set -g history-limit 10000

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# renumber windows
bind R \
  move-window -r\; \
  display-message "Windows reordered..."

# bell
#set-window-option -g window-status-bell-style fg=colour235,bg=colour160 #base02, red

# upgrade $TERM
 set -g default-terminal "xterm-256color"
set -sa terminal-overrides ",xterm-256color:RGB"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'mblum14/tmux-onedark-theme'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'jbnicolai/tmux-fpp'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @tmux-gruvbox 'dark'
set -g @onedark_time_format "%I:%M %p"
set -g @onedark_date_format "%D"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

