SEGMENTS_PATH_COLOR_PRIMARY=$color2
SEGMENTS_PATH_COLOR_SECONDARY=$color7

SEGMENTS_GIT_COLOR_PRIMARY=$color7
SEGMENTS_GIT_COLOR_SECONDARY=$color1

SEGMENTS_PYTHON_ENV_COLOR_PRIMARY=$color10
SEGMENTS_PYTHON_ENV_COLOR_SECONDARY=$color1

SEGMENTS_NODEJS_COLOR_PRIMARY=$color11
SEGMENTS_NODEJS_COLOR_SECONDARY=$color1

SEGMENTS_RUST_COLOR_PRIMARY=$color15
SEGMENTS_RUST_COLOR_SECONDARY=$color1

SEGMENTS_AWS_COLOR_PRIMARY=$color10
SEGMENTS_AWS_COLOR_SECONDARY=$color1

SEGMENTS_COMMAND_COLOR_PRIMARY=$color0
SEGMENTS_COMMAND_COLOR_SECONDARY=$color11
SEGMENTS_COMMAND_COLOR_PRIMARY_HIGHLIGHT=$color0
SEGMENTS_COMMAND_COLOR_SECONDARY_HIGHLIGHT=$color15
