SBP_THEME_COLOR='gruvbox'
SBP_THEME_LAYOUT='powerline'

SBP_HOOKS=('alert')

if [[ "$COLUMNS" -le 120 ]]; then
  SBP_SEGMENTS_LEFT=('path' 'git')
  SBP_SEGMENTS_LINE_TWO=('exit_code' 'prompt_ready')
else
  SBP_SEGMENTS_LEFT=('aws' 'rust' 'nodejs' 'python_env' 'path' 'git')
  SBP_SEGMENTS_LINE_TWO=('command' 'prompt_ready')
fi

SEGMENTS_LOAD_THRESHOLD=50
SEGMENTS_LOAD_THRESHOLD_HIGH=80
SEGMENTS_RESCUETIME_REFRESH_RATE=600
SEGMENTS_TIMESTAMP_FORMAT="%H:%M:%S"
