[directories]
cache_dir = "/alt/.local/state/.tealdeer-cache"

[display]
compact = false
use_pager = false

# colors: black, red, green, yellow, blue, magenta, cyan, white

[style.description]
foreground = "white"
#background = ""
#underline = false
#bold = false
#italic = false

[style.command_name]
foreground = { ansi = 10 }
bold = true

[style.example_text]
foreground = { ansi = 12 }

[style.example_code]
foreground = { ansi = 7 }

[style.example_variable]
foreground =  { ansi = 6 }
underline = true

[updates]
auto_update = true
