local jdtls_ok, jdtls = pcall(require, "jdtls")
if not jdtls_ok then
  vim.notify "JDTLS not found, install with `:LspInstall jdtls`"
  return
end
-- disabled to test out using nvim-lsp

--local root_markers = { ".git", "mvnw", "gradlew", "pom.xml", "build.gradle" }
--local root_dir = jdtls.setup.find_root(root_markers)
--if root_dir == "" then
--  return
--end
--
---- Installation location of jdtls by nvim-lsp-installer
--local JDTLS_LOCATION = vim.fn.stdpath "data" .. "/mason/packages/jdtls"
--local JDTLS_BIN = vim.fn.stdpath("data") .. "/mason/bin/jdtls"
--
---- Data directory - change it to your liking
--local HOME = os.getenv "HOME"
--local project_name = vim.fn.fnamemodify(root_dir, ":p:h:t")
--local workspace_dir = HOME .. "/.cache/jdtls/workspace/" .. project_name
--
---- Only for Linux and Mac
--local SYSTEM = "linux"
--if vim.fn.has "mac" == 1 then
--  SYSTEM = "mac"
--end
--
--local extendedClientCapabilities = jdtls.extendedClientCapabilities
--extendedClientCapabilities.resolveAdditionalTextEditsSupport = true
--
--local on_attach = function(client, bufnr)
--  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
--  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end
--  -- Enable completion triggered by <c-x><c-o>
--  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')
--
--  local opts = { buffer=bufnr, noremap=true, silent=true }
--  wk.register({
--    g = {
--      name = "lsp goto",
--      d = { "<Cmd>lua vim.lsp.buf.definition()<CR>", "Goto definition" },
--      D = { "<Cmd>lua vim.lsp.buf.declaration()<CR>", "Goto declaration" },
--      td = { "<cmd>lua vim.lsp.buf.type_definition()<CR>", "Goto type definition" },
--      i = { "<Cmd>lua vim.lsp.buf.implementation()<CR>", "Goto implementation" },
--      k = { "<Cmd>lua vim.lsp.buf.signature_help()<CR>", "open signature help" },
--      r = { "<Cmd>lua vim.lsp.buf.references()<CR>", "Goto references" },
--      e = { "<Cmd>TroubleToggle<CR>", "Open quickfix" },
--    },
--    ["<leader>"] = {
--      name = "lsp action",
--      w = {
--        name = "workspace",
--        a = { "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>", "Add workspace folder" },
--        r = { "<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>", "Remove workspace folder" },
--        l = { "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>", "List workspace folders" },
--      },
--      rn = { "<cmd>lua vim.lsp.buf.rename()<CR>", "Rename" },
--      ca = { "<cmd>lua vim.lsp.buf.code_action()<CR>", "Code action" },
--      q = { "<cmd>lua vim.diagnostic.setloclist()<CR>", "Set location list" },
--      fm = { "<cmd>lua vim.lsp.buf.formatting()<CR>", "Formatting" },
--    },
--    K = { "<Cmd>lua vim.lsp.buf.hover()<CR>", "Show definition" },
--    ["[d"] = { "<cmd>lua vim.diagnostic.goto_prev()<CR>", "goto previous" },
--    ["]d"] = { "<cmd>lua vim.diagnostic.goto_next()<CR>", "goto next" },
--  }, opts)
--
--
--  -- formatting
--  if client.server_capabilities.document_formatting then
--    vim.api.nvim_command [[augroup Format]]
--    vim.api.nvim_command [[autocmd! * <buffer>]]
--    vim.api.nvim_command [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_seq_sync()]]
--    vim.api.nvim_command [[augroup END]]
--  end
--
--  --protocol.SymbolKind = { }
--  protocol.CompletionItemKind = {
--    '', -- Text
--    '', -- Method
--    '', -- Function
--    '', -- Constructor
--    '', -- Field
--    '', -- Variable
--    '', -- Class
--    'ﰮ', -- Interface
--    '', -- Module
--    '', -- Property
--    '', -- Unit
--    '', -- Value
--    '', -- Enum
--    '', -- Keyword
--    '﬌', -- Snippet
--    '', -- Color
--    '', -- File
--    '', -- Reference
--    '', -- Folder
--    '', -- EnumMember
--    '', -- Constant
--    '', -- Struct
--    '', -- Event
--    'ﬦ', -- Operator
--    '', -- TypeParameter
--  }
--end
--
--local config = {
--  cmd = {
--    JDTLS_BIN,
--  },
--
--  --on_attach = on_attach,
--  --capabilities = require("cmp_nvim_lsp").default_capabilities(vim.lsp.protocol.make_client_capabilities()),
--  root_dir = root_dir,
--
--  -- Here you can configure eclipse.jdt.ls specific settings
--  -- See https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request
--  -- for a list of options
--  settings = {
--    java = {
--      eclipse = {
--        downloadSources = true,
--      },
--      configuration = {
--        updateBuildConfiguration = "interactive",
--      },
--      maven = {
--        downloadSources = true,
--      },
--      implementationsCodeLens = {
--        enabled = true,
--      },
--      referencesCodeLens = {
--        enabled = true,
--      },
--      references = {
--        includeDecompiledSources = true,
--      },
--      format = {
--        enabled = true,
--        settings = {
--          url = vim.fn.stdpath "config" .. "/lang-servers/intellij-java-google-style.xml",
--          profile = "GoogleStyle",
--        },
--      },
--    },
--    signatureHelp = { enabled = true },
--    completion = {
--      favoriteStaticMembers = {
--        "org.hamcrest.MatcherAssert.assertThat",
--        "org.hamcrest.Matchers.*",
--        "org.hamcrest.CoreMatchers.*",
--        "org.junit.jupiter.api.Assertions.*",
--        "java.util.Objects.requireNonNull",
--        "java.util.Objects.requireNonNullElse",
--        "org.mockito.Mockito.*",
--      },
--    },
--    contentProvider = { preferred = "fernflower" },
--    extendedClientCapabilities = extendedClientCapabilities,
--    sources = {
--      organizeImports = {
--        starThreshold = 9999,
--        staticStarThreshold = 9999,
--      },
--    },
--    codeGeneration = {
--      toString = {
--        template = "${object.className}{${member.name()}=${member.value}, ${otherMembers}}",
--      },
--      useBlocks = true,
--    },
--  },
--
--  flags = {
--    allow_incremental_sync = true,
--  },
--  -- Language server `initializationOptions`
--  -- You need to extend the `bundles` with paths to jar files
--  -- if you want to use additional eclipse.jdt.ls plugins.
--  --
--  -- See https://github.com/mfussenegger/nvim-jdtls#java-debug-installation
--  --
--  -- If you don't plan on using the debugger or other eclipse.jdt.ls plugins you can remove this
--  init_options = {
--    bundles = {},
--  },
--}
---- This starts a new client & server,
---- or attaches to an existing client & server depending on the `root_dir`.
--jdtls.start_or_attach(config)
--
---- Add the commands
--require("jdtls.setup").add_commands()
---- vim.api.nvim_exec(
----   [[
---- command! -buffer -nargs=? -complete=custom,v:lua.require'jdtls'._complete_compile JdtCompile lua require('jdtls').compile(<f-args>)
---- command! -buffer -nargs=? -complete=custom,v:lua.require'jdtls'._complete_set_runtime JdtSetRuntime lua require('jdtls').set_runtime(<f-args>)
---- command! -buffer JdtUpdateConfig lua require('jdtls').update_project_config()
---- command! -buffer JdtJol lua require('jdtls').jol()
---- command! -buffer JdtBytecode lua require('jdtls').javap()
---- command! -buffer JdtJshell lua require('jdtls').jshell(),
----   ]],
----   false
---- )
--
--vim.bo.shiftwidth = 2
--vim.bo.tabstop = 2
